### ISSUE TITLE
The link from Part 1 to Part 2 is broken

### ISSUE THREAD

**Issue by cclauss** [7WebPages/snakepit-game#4]
Go to https://7webpages.com/blog/writing-online-multiplayer-game-with-python-asyncio-getting-asynchronous/ and scroll to the bottom and click the link `Part 2. Writing Game Loop`.  Instead of taking you to Part 2, it will merely refresh the page that you are already on.

**Comment by iulia-link** [comment]
Thanks a lot! You liked the article, right? Maybe you have some topics we could write about?

**Comment by cclauss** [comment]
Yes...  I was attracted to it because I was writing http://python3wos.mybluemix.net/ which uses asyncio and aiohttp to download and process 5000 web pages in 20 seconds and show the results on an aiohttp.web website.  I did not get to use websockets so your example was interesting to me.
